# Site settings
title: Florence As It Was&#58;
subtitle: the Digital Reconstruction of a Medieval City
email: florenceasitwas@wlu.edu
email2: bentg@wlu.edu
description: A Washington & Lee Digital Humanities Project
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://florenceasitwas.wlu.edu" # the base hostname & protocol for your site
author: Professor George Bent
street_address: 204 W. Washington St.
city: Lexington
state: VA
zip_code: 24450
country: United States of America
phone: (540) 458-8400

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/florenceasitwas
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/florenceasitwas

# Build settings
markdown: kramdown
excerpt_separator: <!-- more -->

# Collections
collections:
  art:
    output: true
    permalink: /art/:name:output_ext
  architecture:
    output: true
    permalink: /architecture/:name:output_ext
  contributors:
    output: true
    permalink: /contributors/:name:output_ext
  culture:
    output: true
    permalink: /culture/:name:output_ext
  people:
    output: true
    permalink: /people/:name:output_ext
  sites:
    output: true
    permalink: /sites/:name:output_ext
  texts:
    output: true
    permalink: /texts/:name:output_ext
